### ISSUE TITLE
Please allow an option to not format all bootable disks when the installation starts

### ISSUE THREAD

**Issue by rodneyricks** [openshift/assisted-installer#268]
The OpenShift assisted installer says it will format all bootable disks when the installation starts.
Please allow an option to choose which disks to format, or to only format the installation disk.
I have several local drives I don't want formatted, and temporarily disabling them is not a viable option.

**Comment by eranco74** [comment]
Note, The assisted-installer is "[formating](https://github.com/openshift/assisted-service/blob/d37ac44051be76e95676f33b8361c04eae290357/internal/host/hostcommands/install_cmd.go#L232)" (Set the first 512 bytes to 0)  all bootable disks in order to ensure that the host will boot from the installation disk (The assisted-installer also set the boot order via uefi when possible).
